### ISSUE TITLE
npm test failing at loading express responds to /check_payment/:address:

### ISSUE THREAD

**Issue by naqvijafar91** [Overtorment/Cashier-BTC#1]
storage
    get_document()
      ✓ should return any db document
    save_address() && get_address()
      ✓ should save document with address data, and get it back (77ms)
    save_payout()
      ✓ saves document with details on the payout (49ms)
    save_seller()
      ✓ saves document with details on the seller (59ms)

  blockchain
    #create_transaction()
      ✓ should return valid TX hex (54ms)
      ✓ should correctly consider all used inputs

  9 passing (1m)
  6 failing

  1) loading express responds to /check_payment/:address:
     Uncaught Error: getaddrinfo ENOTFOUND http http:80
      at errnoException (dns.js:26:10)
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)

  2) loading express "after each" hook for "responds to /check_payment/:address":
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  

  3) blockchain #broadcast_transaction() should broadcast TX:
     Uncaught Error: getaddrinfo ENOTFOUND http://35.154.27.8 http://35.154.27.8:3001
      at errnoException (dns.js:26:10)
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)

  4) blockchain #fetch_transactions_by_address() should return TXs by address :
     Uncaught Error: getaddrinfo ENOTFOUND http http:80
      at errnoException (dns.js:26:10)
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)

  5) blockchain #fetch_transactions_by_address() should return all TXs:
     Uncaught Error: getaddrinfo ENOTFOUND http http:80
      at errnoException (dns.js:26:10)
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)

  6) blockchain #get_address() should return balances associated with this address :
     Uncaught Error: getaddrinfo ENOTFOUND http http:80
      at errnoException (dns.js:26:10)
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)

**Comment by Overtorment** [comment]
looks like smth is wrong with configuration: `getaddrinfo ENOTFOUND http`
can you show the config?
PS. Just pushed latest version with small fixes

**Comment by naqvijafar91** [comment]
I want to build a feature by which we can use anyone's extended private key to generate addresses so that we can generate as many addresses as we want without the ability to spend them(because this needs a private key). Can you suggest anything, i just need to modify the code regarding address generation and i have seen that in the existing codebase we are generating a new private key using bitcore.js and storing it along with the address and other invoice details in the database.
