### ISSUE TITLE
Trouble with Sync

### ISSUE THREAD

**Issue by ianrussel** [Overtorment/Cashier-BTC#15]
Hi, I tried running below command

      mkdir datadir

Then

          ./bin/bitcoind -port=8444 -rpcport=8442 -datadir=./datadir -rpcuser=user  -rpcpassword=pass -rpcbind=0.0.0.0  -rpcallowip=44.33.22.11

After 30 minutes or so nothing happens, is it an error or what I am doing wrong? I check debug.log and shows this many lines, but no signs of error. I am on windows using ubuntu 16 in a virtualbox machine

      2018-01-06 08:09:10 UpdateTip: new best=000000
      2018-01-06 08:09:10 UpdateTip: new best=000000

**Comment by Overtorment** [comment]
It should be fine as long as datadir grows. Its downloading the blockchain.
You can relaunch it in daemon mode so it run in the background.

**Comment by ianrussel** [comment]
I am closing this issue now, as @Overtorment comment very informative.
