### ISSUE TITLE
Feature to enable merchant's extended private key as a seed to generate derived addresses for merchant

### ISSUE THREAD

**Issue by naqvijafar91** [Overtorment/Cashier-BTC#2]
I want to build a feature by which we can use anyone's extended private key to generate addresses so that we can generate as many addresses as we want without the ability to spend them(because this needs a private key). Can you suggest anything, i just need to modify the code regarding address generation and i have seen that in the existing codebase we are generating a new private key using bitcore.js and storing it along with the address and other invoice details in the database.

**Comment by Overtorment** [comment]
As a quick fix I can suggest you take a look here https://github.com/Overtorment/Cashier-BTC/blob/master/models/storage.js#L82
`seller` is a final address to where coins from orders are transfered. And then using `payout` call you transfer coins from that final address  where you want.  
`seller` is created with random address if doesnt exist previously. You can hardcode your own address (and  dont put private key there), so coins from intermediate `order` addresses will be agregated there directly.
This happens win `worker2.js` file.

Does this make sense?

**Comment by naqvijafar91** [comment]
I want to generate new addresses using the merchant's extended public key, similar to what happens in HD wallets, can you share your share your skype id with me at naqvi.jafar91@gmail.com so that we can collaborate on this thing together ?

**Comment by Overtorment** [comment]
@naqvijafar91 sorry bro, you on your own here. Start digging from here:  https://github.com/Overtorment/Cashier-BTC/blob/master/models/storage.js#L47
