### ISSUE TITLE
getting error when worker2.js transferring amount

### ISSUE THREAD

**Issue by guru439** [Overtorment/Cashier-BTC#22]
[
  'broadcasting',
  '010000000001018b0b33aed894fab40f8b2169cd6ef4fe9698d0ceda169995ebb14f1ef616977c0000000017160014f66fce40a9defb9bf913452dcdea39d1ae8c005affffffff01000000000000000017a914b84e23ed387fdeb8f85f8aff075e98bb8d83e5ec870247304402201f95722f6115fe44c2e393530b0efe483e02d418865aad928f920a52d760cd6a022053ea25cd1ac4ce47b7b778fb2a9a95d0193ac34ed2dbbacaf1fe51f22e99abdd0121034a153f20b6571c58a9751d5fb62f8452941d86a4949b0546712f9702d40e6dbb00000000'
]
(node:10594) UnhandledPromiseRejectionWarning: Error: {"result":null,"error":{"code":-26,"message":"dust (code 64)"},"id":"b7ede744-211a-4603-a95b-328b2d3901b0"}

    at IncomingMessage.<anonymous> (/root/Cashier-BTC/node_modules/jayson/lib/client/http.js:74:21)
    at IncomingMessage.emit (events.js:208:15)
    at endReadableNT (_stream_readable.js:1168:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
(node:10594) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10594) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Overtorment** [comment]
The amount is too small. This is now considered dust.
You can redeem it tho, if you manually craft a transaction and include this
input with a bunch of other inputs.

**Comment by guru439** [comment]
thanks found the bug
