### ISSUE TITLE
Mining fee is too low and things crash if amount being sent is less than the tx fee.

### ISSUE THREAD

**Issue by markasoftware** [Overtorment/Cashier-BTC#4]
The 20,000 satoshi fee is going to make tx confirmation pretty slow today, should be more like 50,000 (or configurable). Additionally, if the amount being transferred to seller wallet is less than the transaction fee, it crashes because 0.0001 - 0.0002 = -0.0001 and bitcore gives an error with negative amounts...

**Comment by Overtorment** [comment]
PRs welcome
